import { create } from 'zustand';
import type { FormStore } from '../types/types';

export const useFormStore = create<FormStore>((set) => ({
  submissions: [],

  countries: [
    'Ukraine',
    'Poland',
    'Germany',
    'France',
    'Italy',
    'Spain',
    'Portugal',
    'United Kingdom',
    'Ireland',
    'Netherlands',
    'Belgium',
    'Switzerland',
    'Austria',
    'Czech Republic',
    'Slovakia',
    'Hungary',
    'Romania',
    'Bulgaria',
    'Greece',
    'Croatia',
    'Serbia',
    'Slovenia',
    'Bosnia and Herzegovina',
    'North Macedonia',
    'Albania',
    'Sweden',
    'Norway',
    'Denmark',
    'Finland',
    'Estonia',
    'Latvia',
    'Lithuania',
    'United States',
    'Canada',
    'Mexico',
    'Brazil',
    'Argentina',
    'Chile',
    'Colombia',
    'Peru',
    'Japan',
    'South Korea',
    'China',
    'India',
    'Thailand',
    'Vietnam',
    'Indonesia',
    'Malaysia',
    'Philippines',
    'Australia',
    'New Zealand',
    'South Africa',
    'Egypt',
    'Morocco',
    'Turkey',
    'Saudi Arabia',
    'United Arab Emirates',
    'Israel',
    'Other',
  ],

  addSubmission: (submission) =>
    set((state) => ({
      submissions: [submission, ...state.submissions],
    })),
}));
